# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START cloudbuild_sql_proxy]
steps:
  # Run tests and save to file
  - name: golang:1.16
    entrypoint: /bin/bash
    env:
      - "DATABASE_NAME=${_DATABASE_NAME}"
      - "DATABASE_USER=${_DATABASE_USER}"
      - "INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}"
      - "DATABASE_TYPE=${_DATABASE_TYPE}"
    secretEnv:
      - DATABASE_PASS
      - CRED_FILE
    args: 
      - -c
      - |
        go install github.com/jstemmer/go-junit-report/v2@latest
        2>&1 go test -timeout 1m -v ./... | /go/bin/go-junit-report -set-exit-code -iocopy -out ${SHORT_SHA}_test_log.xml
        go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
        migrate -version
        wget -O /workspace/cloud_sql_proxy https://storage.googleapis.com/cloudsql-proxy/v1.15/cloud_sql_proxy.linux.386 && chmod +x /workspace/cloud_sql_proxy        
        bash workspace/env.sh
        db_pass=$(cat DB_PASS)
        /workspace/cloud_sql_proxy -dir=/workspace -instances=${_INSTANCE_CONNECTION_NAME}=tcp:3306 -credential_file=cloud-sa.json & sleep 2 && \
        migrate -database "mysql://${_DATABASE_USER}:${db_pass}@(127.0.0.1:3306)/test_db" -path "./migrator/migrations/" up

options:
  dynamic_substitutions: true

substitutions:
  _DATABASE_USER: sandbox_user
  _DATABASE_NAME: test_db
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:us-central1:lighthousedb
  _DATABASE_PORT: '3306'
  _DATABASE_TYPE: mysql
  _DATABASE_PASSWORD_KEY: lh-sandbox-db-pwd
  _IMAGE_NAME: gcr.io/${PROJECT_ID}/sample-sql-proxy

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_PASSWORD_KEY}/versions/latest
      env: DATABASE_PASS
    - versionName: projects/$PROJECT_ID/secrets/cloud-sa-key/versions/latest
      env: CRED_FILE
# [END cloudbuild_sql_proxy]
