version: 2.1
executors:
  go-build:
    docker:
      - image: quay.io/getpantheon/go-build:latest
        auth:
          username: $QUAY_USER
          password: $QUAY_PASSWD
commands:  
  set_project:
    description: Command to set project
    steps:
      - run: |
          sudo apt-get install -qq -y gettext
          echo ${cideployer} > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    working_directory: ~/project
    environment:
      PROJECT_NAME: "db-migration-dev"
      GOOGLE_PROJECT_ID: "pantheon-buildhook"
      GOOGLE_COMPUTE_REGION: "us-central1"
      ENV_NAME: dev
    steps:
      - checkout
      - set_project
      - run: |
          gcloud builds submit --region=us-central1 --config sql/cloudbuild.yaml sql --substitutions=_ENV_NAME="${ENV_NAME}"
  
  db_migration:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/project
    environment:
      PROJECT_NAME: "db-migration-dev"
      GOOGLE_PROJECT_ID: "pantheon-buildhook"
    steps:
      - checkout
      - set_project
      - run:
          command: |
            gcloud config get-value project

workflows:
  version: 2
  test_my_app:
    jobs:
      - build
    # - db_migration
