version: 2.1
executors:
  go-build:
    docker:
      - image: quay.io/getpantheon/go-build:latest
        auth:
          username: $QUAY_USER
          password: $QUAY_PASSWD
commands:  
  set_project:
    description: Command to set project
    steps:
      - run: |
          sudo apt-get install -qq -y gettext
          echo ${cideployer} > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    working_directory: ~/project
    environment:
      PROJECT_NAME: "db-migration-dev"
      GOOGLE_PROJECT_ID: "pantheon-buildhook"
      GOOGLE_COMPUTE_REGION: "us-central1"
      ENV_NAME: dev
    steps:
      - checkout
      - set_project
      - run: |
          echo "testing approval flow"    
  
  build2:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    working_directory: ~/project
    environment:
      PROJECT_NAME: "db-migration-dev"
      GOOGLE_PROJECT_ID: "pantheon-buildhook"
      GOOGLE_COMPUTE_REGION: "us-central1"
      ENV_NAME: dev
    steps:
      - checkout
      - set_project
      - run: |
          echo "build2"
  
  deploy_to_sandbox:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    working_directory: ~/project
    environment:
      PROJECT_NAME: "db-migration-dev"
      GOOGLE_PROJECT_ID: "pantheon-buildhook"
      GOOGLE_COMPUTE_REGION: "us-central1"
      ENV_NAME: prod
    steps:
      - checkout
      - run: |
          echo ${cideployer} > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud builds submit --region=us-central1 --config sql/cloudbuild.yaml sql --substitutions=_ENV_NAME="${ENV_NAME}"
  
  deploy_to_sandbox_new:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/project
    environment:
      PROJECT_NAME: "buildhook-service-sbx"
      GOOGLE_PROJECT_ID: "pantheon-buildhook"
      FUNCTION_NAME: "buildhook-service-sbx"
      ENTRYPOINT: BuildhookEntry
      BUCKNAME: "buildhook-service"
    steps:
      - checkout
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo ${cideployer} > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json      
      - run:
          name: Deploy To Google Cloud Functions
          command: |
            echo "hello world"
  
  deploy_prod:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    working_directory: ~/project
    environment:
      PROJECT_NAME: "db-migration-dev"
      GOOGLE_PROJECT_ID: "pantheon-buildhook"
      GOOGLE_COMPUTE_REGION: "us-central1"
      ENV_NAME: dev
    steps:
      - checkout
      - run: |
          echo "deploy to prod"
  
workflows:
  version: 2
  test_my_app:
    jobs:
      - build
      - hold_sandbox_deployment:
          type: approval           
          filters:
            branches:
              only:
                - main      
      - deploy_to_sandbox:
          requires:
            - hold_sandbox_deployment
          filters:
            branches:
              only:
                - main
      - hold_prod_deployment:
          type: approval
          requires:
            - deploy_to_sandbox
          filters:
            branches:
              only:
                - main
      - deploy_prod:
          requires:
            - hold_prod_deployment
          filters:
            branches:
              only:
                - main
        

# - db_migration

# workflows:
#   version: 2
#   test-build-deploy:
#     jobs:
#       - test
#       - hold_sandbox_deployment:
#           type: approval
#           requires:
#             - sandbox-db-migration
#           filters:
#             branches:
#               only:
#                 - main
#       - deploy_to_sandbox:
#           requires:
#             - hold_sandbox_deployment
#           filters:
#             branches:
#               only:
#                 - main
#       - hold_prod_deployment:
#           type: approval
#           requires:
#             - deploy_to_sandbox
#             - prod-db-migration
#           filters:
#             branches:
#               only:
#                 - main
#       - deploy_to_prod:
#           requires:
#             - hold_prod_deployment
#           filters:
#             branches:
#               only:
#                 - main
